FROM centos:latest

RUN cd /etc/yum.repos.d/

RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*

RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

RUN yum install java-11-openjdk -y

RUN yum install wget -y

RUN mkdir /opt/tomcat

WORKDIR /opt/tomcat

RUN wget https://www-eu.apache.org/dist/tomcat/tomcat-9/v9.0.27/bin/apache-tomcat-9.0.27.tar.gz

RUN tar -xvzf apache-tomcat-9.0.27.tar.gz

RUN mv apache-tomcat-9.0.27.tar.gz/* /opt/tomcat

EXPOSE 8080

CMD ["/opt/tomcat/bin/catalina.sh", "run"]
