FROM ubuntu

RUN apt-get update

ENV TZ=Asia/Dubai

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt install -y tzdata

RUN apt install -y git

RUN apt install apache2 -y

EXPOSE 80
